// Vordefinierte Kategorien für das Assoziationsspiel
const CATEGORIES = [

  // ── Tiere ─────────────────────────────────────────────────────────────────
  "Tiere im Zoo",
  "Haustiere",
  "Meerestiere",
  "Vögel",
  "Insekten",
  "Säugetiere",
  "Reptilien",
  "Amphibien",
  "Raubtiere",
  "Nutztiere",
  "Tiere in der Wüste",
  "Tiere im Dschungel",
  "Tiere in der Arktis",
  "Tiere die nachts aktiv sind",
  "Giftige Tiere",
  "Ausgestorbene Tiere",
  "Tiere die fliegen können",
  "Tiere die im Wasser leben",
  "Kleine Tiere",
  "Große Tiere",

  // ── Natur & Pflanzen ──────────────────────────────────────────────────────
  "Bäume",
  "Blumen",
  "Früchte",
  "Gemüse",
  "Pilze",
  "Kräuter",
  "Kakteen",
  "Tropische Pflanzen",
  "Naturkatastrophen",
  "Wetterphänomene",
  "Berge & Gipfel",
  "Seen",
  "Flüsse",
  "Wälder",
  "Wüsten",
  "Ozeane",
  "Jahreszeiten",
  "Mineralien & Gesteine",

  // ── Orte & Geographie ─────────────────────────────────────────────────────
  "Hauptstädte",
  "Deutsche Städte",
  "Länder in Europa",
  "Länder in Asien",
  "Länder in Afrika",
  "Länder in Südamerika",
  "Inseln",
  "Gebirge",
  "Strände",
  "Berühmte Sehenswürdigkeiten",
  "UNESCO-Welterbestätten",
  "Europäische Hauptstädte",
  "Amerikanische Städte",
  "Asiatische Metropolen",
  "Touristenattraktionen in Deutschland",
  "Berühmte Plätze der Welt",
  "Nationalparks",
  "Historische Städte",
  "Städte am Meer",

  // ── Essen & Trinken ───────────────────────────────────────────────────────
  "Fastfood",
  "Desserts & Süßigkeiten",
  "Käsesorten",
  "Cocktails",
  "Frühstücksgerichte",
  "Italienische Gerichte",
  "Gewürze",
  "Snacks",
  "Brotaufstriche",
  "Suppenarten",
  "Kuchenarten",
  "Eissorten",
  "Pizzabeläge",
  "Pasta-Sorten",
  "Grillgerichte",
  "Streetfood",
  "Vegetarische Gerichte",
  "Asiatische Gerichte",
  "Mexikanische Gerichte",
  "Deutsche Gerichte",
  "Frühstücksflocken",
  "Kräutertees",
  "Limonaden & Softdrinks",
  "Biersorten",
  "Weinsorten",
  "Nüsse & Kerne",
  "Gewürzsaucen",
  "Frühstücksgerichte am Wochenende",
  "Dinge auf einer Speisekarte",
  "Zutaten für einen Salat",

  // ── Film & Serien ─────────────────────────────────────────────────────────
  "Marvel-Helden",
  "Marvel-Schurken",
  "Disney-Figuren",
  "Disney-Prinzessinnen",
  "Zeichentrickserien",
  "Netflix-Serien",
  "Horrorfilme",
  "Komödien",
  "Actionfilme",
  "Animationsfilme",
  "Filmklassiker",
  "Sci-Fi-Filme",
  "Romanzen im Kino",
  "Oscar-Gewinner",
  "Filmreihen & Franchises",
  "Berühmte Filmzitate",
  "Superhelden",
  "Bösewichte in Filmen",
  "Pixar-Filme",
  "James Bond Filme",
  "Star Wars Charaktere",
  "Harry Potter Charaktere",
  "Herr der Ringe Charaktere",
  "Serien mit mehr als 5 Staffeln",
  "Reality-TV-Shows",
  "Krimi-Serien",
  "Arzt-Serien",

  // ── Musik ─────────────────────────────────────────────────────────────────
  "Musiker & Bands",
  "Musikgenres",
  "Musikinstrumente",
  "Berühmte Alben",
  "Musikfestivals",
  "Deutschsprachige Künstler",
  "Hip-Hop-Künstler",
  "Pop-Sängerinnen",
  "Rockbands",
  "DJs",
  "Klassische Komponisten",
  "Musikpreise",
  "Songtitel mit Farbe drin",
  "Eurovision-Teilnehmer",
  "Dinge in Songtexten",
  "Musikvideos",

  // ── Sport ─────────────────────────────────────────────────────────────────
  "Sportarten",
  "Olympische Sportarten",
  "Fußballvereine",
  "Fußballspieler",
  "Tennisspieler",
  "Formel-1-Fahrer",
  "Boxweltmeister",
  "Schwimmer",
  "Leichtathletik-Disziplinen",
  "Wintersportarten",
  "Wassersportarten",
  "Extremsportarten",
  "Kampfsportarten",
  "Ballsportarten",
  "Sportgeräte",
  "Sportstätten & Stadien",
  "Olympia-Gastgeberstädte",
  "Berühmte Sportmomente",
  "eSports-Spiele",
  "Brettspiele",

  // ── Gaming & Technik ──────────────────────────────────────────────────────
  "Videospiele",
  "Videospiel-Charaktere",
  "Gaming-Konsolen",
  "Handy-Apps",
  "Social-Media-Plattformen",
  "Tech-Unternehmen",
  "Smartphone-Marken",
  "Computer-Begriffe",
  "Roboter & KI in Filmen",
  "Dinge im Internet",
  "Browser",
  "Programmiersprachen",
  "Videospiel-Genres",

  // ── Alltag & Lifestyle ────────────────────────────────────────────────────
  "Berufe",
  "Schuldfächer",
  "Kleidungsstücke",
  "Möbelstücke",
  "Haushaltsgeräte",
  "Transportmittel",
  "Werkzeuge",
  "Dinge im Badezimmer",
  "Dinge im Schlafzimmer",
  "Dinge in der Küche",
  "Dinge in einem Rucksack",
  "Dinge auf einem Schreibtisch",
  "Dinge an einem Bahnhof",
  "Dinge an einem Flughafen",
  "Dinge in einer Handtasche",
  "Dinge in einem Supermarkt",
  "Hobbys",
  "Urlaubsaktivitäten",
  "Partyspiele",
  "Kindergartenaktivitäten",
  "Dinge die man im Urlaub braucht",
  "Dinge in einem Hotel",
  "Dinge auf einem Festival",

  // ── Mode & Beauty ─────────────────────────────────────────────────────────
  "Modemarken",
  "Schuharten",
  "Accessoires",
  "Parfüm-Marken",
  "Frisuren",
  "Make-up-Produkte",
  "Schmuck",
  "Streetwear-Marken",
  "Designermarken",

  // ── Wissen & Wissenschaft ─────────────────────────────────────────────────
  "Planeten",
  "Sternbilder",
  "Elemente aus dem Periodensystem",
  "Erfindungen",
  "Berühmte Wissenschaftler",
  "Körperteile",
  "Dinosaurier",
  "Krankheiten",
  "Mathematische Begriffe",
  "Chemische Reaktionen",
  "Physikalische Kräfte",
  "Medizinische Geräte",
  "Tierreich-Klassifikationen",
  "Geologische Epochen",
  "Raumfahrtmissionen",
  "Nobelpreisträger",

  // ── Geschichte & Politik ──────────────────────────────────────────────────
  "Historische Persönlichkeiten",
  "Historische Schlachten",
  "Antike Reiche",
  "Revolutionen",
  "Berühmte Herrscher",
  "Alte Kulturen",
  "Historische Erfindungen",
  "Weltkrieg-Ereignisse",
  "Berühmte Reden",
  "Politische Systeme",
  "Internationale Organisationen",
  "Berühmte Entdecker",

  // ── Menschen & Gesellschaft ───────────────────────────────────────────────
  "Berühmte Frauen der Geschichte",
  "Berühmte Männer der Geschichte",
  "Schauspieler",
  "Schauspielerinnen",
  "YouTuber",
  "Influencer",
  "Comedians",
  "Politiker",
  "Schriftsteller",
  "Maler & Künstler",
  "Architekten",
  "Modelle",
  "Berühmte Duos",
  "Berühmte Paare",

  // ── Farben, Formen & Sinne ────────────────────────────────────────────────
  "Farben",
  "Formen",
  "Farben im Regenbogen",
  "Dinge die rot sind",
  "Dinge die blau sind",
  "Dinge die gelb sind",
  "Dinge die rund sind",
  "Dinge die eckig sind",
  "Dinge die weich sind",
  "Dinge die hart sind",
  "Dinge die leuchten",
  "Dinge die stinken",
  "Dinge die gut riechen",
  "Dinge die laut sind",
  "Dinge die leise sind",
  "Dinge die kalt sind",
  "Dinge die heiß sind",
  "Dinge die klebrig sind",

  // ── Kreativ & Spaß ────────────────────────────────────────────────────────
  "Superkräfte",
  "Dinge auf einem Spielplatz",
  "Dinge an einem Strand",
  "Dinge im Kühlschrank",
  "Dinge die schnell sind",
  "Dinge die langsam sind",
  "Dinge die man sammeln kann",
  "Dinge die man nicht essen sollte",
  "Dinge auf einem Jahrmarkt",
  "Dinge in einem Märchen",
  "Dinge die man auf einer einsamen Insel mitnehmen würde",
  "Dinge die man in einer Zeitkapsel einschließen würde",
  "Dinge die Kinder lieben",
  "Dinge die Erwachsene lieben",
  "Dinge die nervös machen",
  "Dinge die entspannen",
  "Dinge die man bei Regen macht",
  "Dinge die man bei Sonnenschein macht",
  "Dinge die man im Winter macht",
  "Dinge die man im Sommer macht",
  "Gegensätze",
  "Dinge in einem Zauberkasten",
  "Dinge in einem Piratenversteck",
  "Dinge in einem Hexenkessel",
  "Dinge in einer Zeitmaschine",

  // ── Sprache & Kommunikation ───────────────────────────────────────────────
  "Sprachen der Welt",
  "Schriftzeichen & Alphabete",
  "Emojis",
  "Redewendungen",
  "Schimpfwörter (harmlos)",
  "Spitznamen",
  "Dinge die man flüstert",
  "Dinge die man schreit",

  // ── Zahlen & Mengen ───────────────────────────────────────────────────────
  "Zahlen",
  "Dinge die es in Paaren gibt",
  "Dinge die drei von etwas haben",
  "Dinge die sehr teuer sind",
  "Dinge die sehr billig sind",
  "Dinge die man zählen kann",

  // ── Jahreszeiten & Feiertage ──────────────────────────────────────────────
  "Weihnachtssymbole",
  "Halloween-Symbole",
  "Ostersymbole",
  "Geburtstagsdinge",
  "Silvester-Traditionen",
  "Valentinstag-Symbole",
  "Karnevalskostüme",
  "Feiertage weltweit",

  // ── Fahrzeuge & Transport ─────────────────────────────────────────────────
  "Automarken",
  "Motorradmarken",
  "Flugzeugtypen",
  "Schiffstypen",
  "Züge & Bahnen",
  "Rennfahrzeuge",
  "Militärfahrzeuge",
  "Dinge an einem Auto",
  "Fahrradtypen",

  // ── Architektur & Gebäude ─────────────────────────────────────────────────
  "Gebäudetypen",
  "Berühmte Brücken",
  "Berühmte Türme",
  "Kirchen & Kathedralen",
  "Burgen & Schlösser",
  "Moderne Architektur",
  "Dinge in einem Haus",
  "Räume in einem Haus",

  // ── Tiere (ergänzt) ───────────────────────────────────────────────────────
  "Hunderassen",
  "Katzenrassen",
  "Pferderassen",
  "Vogelarten in Deutschland",
  "Schmetterlingsarten",
  "Fischarten",
  "Haie",
  "Primaten",
  "Nagetiere",
];

module.exports = CATEGORIES;
